### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by ramiel** [hbldh/sudokuextract#2]
Hello. I'm trying to install this package but I get this error during install of scikit-image

```
Collecting scikit-image<0.12.0 (from sudokuextract)
  Downloading https://files.pythonhosted.org/packages/02/67/7f44f79b981413d72ffe505c3fa06f9d0c20a2ad944503bf7395deb7930d/scikit-image-0.11.3.tar.gz (18.6MB)
    100% |████████████████████████████████| 18.6MB 86kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Nf3Z8M/scikit-image/setup.py", line 77, in <module>
        import scipy
    ImportError: No module named scipy
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Nf3Z8M/scikit-image/
```

How can I solve?

**Comment by hbldh** [comment]
This project is not maintained at all any longer, and I have little time to help you with this. 
It does seem to be a `scikit-image` problem more than it is a `sudokuextract` problem...

**Comment by ramiel** [comment]
Ok, don't worry. Thank you
