### ISSUE TITLE
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead

### ISSUE THREAD

**Issue by s-raza** [hbldh/sudokuextract#3]
I encountered the below error, on my first run after installing sudokoextract through pip. The error is fixed by replacing "-" with "~" in the source code. I will be creating a pull request with a reference to this issue.

**$parse-sudoku -p sudoku1.jpg**
Traceback (most recent call last):
  File "/opt/progs/py2venv-2/bin/parse-sudoku", line 8, in <module>
    sys.exit(main())
  File "/opt/progs/py2venv-2/local/lib/python2.7/site-packages/sudokuextract/extract.py", line 63, in main
    preds, images, subimage = extract_sudoku(image)
  File "/opt/progs/py2venv-2/local/lib/python2.7/site-packages/sudokuextract/extract.py", line 33, in extract_sudoku
    predictions, sudoku_box_images, subimage = method(image, classifier)
  File "/opt/progs/py2venv-2/local/lib/python2.7/site-packages/sudokuextract/methods/map.py", line 31, in extraction_method_map
    for sudoku, subimage in _extraction_iterator_map(image, use_local_thresholding, apply_gaussian, n=n):
  File "/opt/progs/py2venv-2/local/lib/python2.7/site-packages/sudokuextract/methods/map.py", line 60, in _extraction_iterator_map
    for edges in iter_blob_contours(img, n=n):
  File "/opt/progs/py2venv-2/local/lib/python2.7/site-packages/sudokuextract/imgproc/blob.py", line 51, in iter_blob_contours
    bimg = (-binary_erosion(bimg))
**_TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead._**
**$python --version**
Python 2.7.15+

**Comment by hbldh** [comment]
Fixed by #4
